### ISSUE TITLE
error: no member named 'abs' in namespace 'std'

### ISSUE THREAD

**Issue by ryandesign** [raceintospace/raceintospace#362]
Hello, the latest raceintospace code as of yesterday 2020-06-03 (8ff7814d5e2b6e73a817ead6c76eeb8823d4e3d7) doesn't build on OS X 10.11 or 10.9. The error is:

```
/opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_games_raceintospace/raceintospace/work/raceintospace-8ff7814d5e2b6e73a817ead6c76eeb8823d4e3d7/src/display/legacy_surface.cpp:91:13: error: no member named 'abs' in namespace 'std'; did you mean simply 'abs'?
    steep = std::abs((int)(y2 - y1)) > std::abs((int)(x2 - x1));
            ^~~~~~~~
            abs
/usr/include/stdlib.h:129:6: note: 'abs' declared here
int      abs(int) __pure2;
         ^
/opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_games_raceintospace/raceintospace/work/raceintospace-8ff7814d5e2b6e73a817ead6c76eeb8823d4e3d7/src/display/legacy_surface.cpp:91:40: error: no member named 'abs' in namespace 'std'; did you mean simply 'abs'?
    steep = std::abs((int)(y2 - y1)) > std::abs((int)(x2 - x1));
                                       ^~~~~~~~
                                       abs
/usr/include/stdlib.h:129:6: note: 'abs' declared here
int      abs(int) __pure2;
         ^
/opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_games_raceintospace/raceintospace/work/raceintospace-8ff7814d5e2b6e73a817ead6c76eeb8823d4e3d7/src/display/legacy_surface.cpp:104:14: error: no member named 'abs' in namespace 'std'; did you mean simply 'abs'?
    deltay = std::abs((int)(y2 - y1));
             ^~~~~~~~
             abs
/usr/include/stdlib.h:129:6: note: 'abs' declared here
int      abs(int) __pure2;
         ^
3 errors generated.
make[2]: *** [src/display/CMakeFiles/raceintospace_display.dir/legacy_surface.cpp.o] Error 1
```

Here is the full [build log from 10.11](https://build.macports.org/builders/ports-10.11_x86_64-builder/builds/115337/steps/install-port/logs/stdio).

It does build fine on macOS 10.13 and later. Here is a [build log from 10.13](https://build.macports.org/builders/ports-10.13_x86_64-builder/builds/85268/steps/install-port/logs/stdio). I did not test 10.10 or 10.12.

In case it is relevant, I am compiling with the `-std=c++11` flag. This is necessary because I am using a version of raceintospace's dependency jsoncpp (1.9.2) that requires C++11 mode or newer.

**Comment by ryandesign** [comment]
It does build fine on Mac OS X 10.7 when using a newer compiler from MacPorts (clang 9.0.1). So this may be one of those things where the standard was changed or relaxed in newer compilers. Of course if there's a way to modify the code so that it works both with old and new compilers that seems desirable given the lengths to which the existing code already goes to support older versions of Mac OS X.

**Comment by rnyoakum** [comment]
I'm wondering if the problem is that the game was ported from C to C++ but the headers never were updated to the C++ standard versions - <stdlib.h> to <cstdlib>, for instance. It hasn't caused any problem on my build, but there might be a compiler-tolerance issue. Since it would be nice to use the C++ versions anyways (this is a C++ project using C++ compilers) I'll work on an update.

**Comment by rnyoakum** [comment]
I added a pull request (#365) that converts the C standard library headers to their C++ counterparts. Would you be willing to check this on OsX and see if it fixes the issue / does nothing / generates more errors?

**Comment by ryandesign** [comment]
Thanks... I verified that it still builds on 10.13 (Apple LLVM version 9.1.0 (clang-902.0.39.2)) but it still fails with the same error under 10.9 (Apple LLVM version 6.0 (clang-600.0.57) (based on LLVM 3.5svn)).

**Comment by ryandesign** [comment]
I found some prior occurrences of this type of error in MacPorts. We've fixed it [once before](https://github.com/macports/macports-ports/blob/7b53ec53c0aebb4eebf3c23b8fbe08a4ae7eac5f/textproc/qpdf/files/abs.patch) by adding `#include <cstdlib>`. [Another time](https://github.com/macports/macports-ports/blob/09f0d4741786cf70b803a88b81260e1aee9e526e/multimedia/mythtv-core.27/files/patch-various_c%2B%2B_v_stdc%2B%2B.diff) we fixed it with `#include <cmath>`. Not sure which is better or more correct.

**Comment by rnyoakum** [comment]
Looking over the code... I think it (src/display/legacy_surface.cpp) needs `<cstdlib>` for `int abs(int n)`, and I would explicitly include `<algorithm>` as well to cover the references to std::min, std::max, and std::swap. I can put in a pull request on a commit if you'd prefer, but since it's a two-line change and I can't test for the error, I was hoping you could quickly demo it. I'd rather not create a pull request that doesn't accomplish anything.

**Comment by ryandesign** [comment]
Yes, just adding `#include <cstdlib>` to src/display/legacy_surface.cpp (with or without your changes from #365) works on OS X 10.9.

**Comment by rnyoakum** [comment]
Thanks for testing that. While my first thought had been it might a compiler-tolerance issue surrounding the std namespace, I think it's actually a chained-include issue. The file src/display/legacy_surface.cpp didn't itself include `<cstdlib>` or `<algorithm>`; the former is needed for std::abs, the latter for std::min, std::max, std::swap. Instead, it was including other headers which provided access to those key headers (presumably, through either the boost or SDL headers). So my hunch is that there's an OS/compiler -dependent define in one of those libraries which was being relied upon.

**Comment by ryandesign** [comment]
> I think it's actually a chained-include issue

I think you're right. I suspect there have simply been changes to the clang headers over time, and that on new versions of clang cstdlib was coincidentally being included by some other header that you were already including, but that that wasn't the case on older versions of clang.
