### ISSUE TITLE
no matching function for call to 'MusicSequenceFileLoadData'

### ISSUE THREAD

**Issue by ryandesign** [raceintospace/raceintospace#307]
Hello,

The latest raceintospace commit as of right now (d6b4649b16c3df4128942e3fe778193e47a7b7b4) doesn't build on macOS 10.13.6. The error (after applying the fix from #306) is:

```
/path/to/src/game/platform_macosx/music_osx.cpp:172:14: error: no matching function for call to 'MusicSequenceFileLoadData'
        rv = MusicSequenceFileLoadData(music_files[track].sequence, CFDataCreate(NULL, (UInt8*)midi_data, fileLength), 0, 0);
             ^~~~~~~~~~~~~~~~~~~~~~~~~
/System/Library/Frameworks/AudioToolbox.framework/Headers/MusicPlayer.h:816:1: note: candidate function not viable: no known conversion from 'int' to 'MusicSequenceFileTypeID' for 3rd argument
MusicSequenceFileLoadData (MusicSequence                        inSequence,
^
1 error generated.
```

**Comment by pemensik** [comment]
@ryandesign I have found [apple documentation](https://developer.apple.com/documentation/audiotoolbox/1502222-musicsequencefileload?language=objc), but it is not very clear to me what possible values there are. Also good resource might be [Xamarin](https://github.com/xamarin/apple-api-docs/tree/master/en/AudioToolbox)

Could you please try this:

rv = MusicSequenceFileLoadData(music_files[track].sequence, CFDataCreate(NULL, (UInt8*)midi_data, fileLength), Any, 0);

**Comment by pemensik** [comment]
if Any does not help, try AnyType instead.

**Comment by TiPunch69** [comment]
I have tried to build it on MacOS 10.15.5 according to the description - the build (target: ### build_all) fails with 24 errors in game_test.
I attached the compiler output.
You can however compile and run the ### raceintospace target, which outputs music and a blank window. The console output of the run is also attached.
Hope it helps.
[runOutput.txt](https://github.com/raceintospace/raceintospace/files/4709759/runOutput.txt)
[Build ALL_BUILD_2020-06-01T08-29-13.txt](https://github.com/raceintospace/raceintospace/files/4709760/Build.ALL_BUILD_2020-06-01T08-29-13.txt)

**Comment by pemensik** [comment]
Thank you, quite useful to me.

Ah! looking at Build All output and cannot guess what is wrong and why. And then oh my God. It is error of game_test target, which is almost irrelevant. src/game/platform_macosx/platform.cmake adds MACOSX_BUNDLE, SDLMain.m and BundleResources. game_test does not any of that. I think we should get rid UI parts from game_test anyway.

**Comment by pemensik** [comment]
I have found https://stackoverflow.com/questions/19348239/sparkle-10-9-linking-error to be related to the first line of runOutput. But I am not sure how to solve this from CMake side. And I am not sure whether this is the main reason of failure.

**Comment by pemensik** [comment]
According to https://github.com/SDL-mirror/SDL/blob/SDL-1.2/README.MacOSX I am not sure where the .nib file came from and whether it is possible to update it. May it be too old to use?

**Comment by TiPunch69** [comment]
I am sorry, I had the totally wrong impression:

By reading through the issue - and especially the "documentation unclear, try to use Any" section -  I had the impression that a compile on an actual Mac system with XCode would help, even if done by a Non-Developer, who is just guessing and providing the output. As I have come to realize that is clearly not the case and you have it all under control and I am therefore confident we will see a Mac version soon.

So all the best then and to everybody who would love to play this game on a Mac I can recommend the old version under DosBox which works quite well for me in the meantime.

**Comment by pemensik** [comment]
I am sorry, but without your help, I can not fix it. Provided output is very helpful, but I do not have any Mac computer to try it myself. Some developer with Mac experience would be more useful.

**Comment by ryandesign** [comment]
We probably want to keep this to one problem per issue so I suggest merging my PR #363 to solve this issue #307 about the music sequence function constants and I'll file new issues for the other unrelated issues brought up here.

**Comment by ryandesign** [comment]
#358 was merged which solves the originally reported problem on 10.13, however it causes a related problem on 10.8 and earlier. See #363 for the correct fix.

**Comment by rnyoakum** [comment]
Sorry, I was looking over the first fix when the #363 pull request came in and didn't see it until after I approved the first merge. I'll merge the second fix. Thank you for your assistance.

**Comment by rnyoakum** [comment]
@ryandesign - I merged your commit. I'm leaving this open until you or someone else with a Mac confirms that the issue is properly fixed, seeing as I can't confirm it myself. Once again, sorry about the earlier mix-up.

**Comment by ryandesign** [comment]
It should be fine now, thanks. See #367 for the hopefully final fix.
