### PR TITLE
Use constants for music sequence functions

### LINKED ISSUE #307: no matching function for call to 'MusicSequenceFileLoadData'
Hello,

The latest raceintospace commit as of right now (d6b4649b16c3df4128942e3fe778193e47a7b7b4) doesn't build on macOS 10.13.6. The error (after applying the fix from #306) is:

```
/path/to/src/game/platform_macosx/music_osx.cpp:172:14: error: no matching function for call to 'MusicSequenceFileLoadData'
        rv = MusicSequenceFileLoadData(music_files[track].sequence, CFDataCreate(NULL, (UInt8*)midi_data, fileLength), 0, 0);
             ^~~~~~~~~~~~~~~~~~~~~~~~~
/System/Library/Frameworks/AudioToolbox.framework/Headers/MusicPlayer.h:816:1: note: candidate function not viable: no known conversion from 'int' to 'MusicSequenceFileTypeID' for 3rd argument
MusicSequenceFileLoadData (MusicSequence                        inSequence,
^
1 error generated.
```

### PR DESCRIPTION
**Pull request by ryandesign**
Using constants is required for newer versions of macOS yet the constants did not exist until the 10.9 SDK so define them if using an earlier SDK.

I verified this builds on OS X 10.7, macOS 10.13, 10.14, 10.15.

Closes #307

### CODE REVIEW

**Comment by ryandesign** [comment]
Looks like #358 was merged instead, but that doesn't define the constants for OS X < 10.9.
